// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-analyses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var notAuthenticated = {
  content: [{ type: "text", text: "Not authenticated." }],
  isError: true
};

// src/lib/mcp/tools/list-analyses.ts
var list_analyses_default = defineTool({
  name: "list_analyses",
  title: "List my analyses",
  description: "List the signed-in user's most recent SonicSIM semantic analyses with their six category scores (emotional, cognitive, social, communication, contextual, artistic), confidence and grounding level.",
  inputSchema: {
    limit: z.number().int().describe("How many analyses to return (1-50, default 10)").optional(),
    search: z.string().describe("Optional case-insensitive filter on the source name.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const take = Math.min(Math.max(Math.round(limit ?? 10), 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("source_analyses").select(
      "id, source_name, category, grounding_level, confidence, created_at, emotional_score, cognitive_score, social_score, communication_score, contextual_score, artistic_score"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(take);
    if (search && search.trim()) query = query.ilike("source_name", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map(
      (r) => `${r.source_name} \u2014 ${r.category ?? "uncategorized"} (${r.grounding_level ?? "text-only"}, confidence ${r.confidence}) \u2014 emotional ${r.emotional_score}, cognitive ${r.cognitive_score}, social ${r.social_score}, communication ${r.communication_score}, contextual ${r.contextual_score}, artistic ${r.artistic_score}`
    ).join("\n") : "No analyses yet.";
    return { content: [{ type: "text", text }], structuredContent: { analyses: rows } };
  }
});

// src/lib/mcp/tools/get-fingerprint.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
var get_fingerprint_default = defineTool2({
  name: "get_fingerprint",
  title: "Get my sonic fingerprint",
  description: "Return the signed-in user's aggregate sonic fingerprint: all-time and last-30-day averages across the six SonicSIM categories, how many sources it is based on, and its confidence.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("user_fingerprints").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [
          { type: "text", text: "No fingerprint yet \u2014 analyze at least one audio source first." }
        ]
      };
    }
    const text = [
      `Fingerprint from ${data.total_sources_analyzed} sources (confidence ${data.fingerprint_confidence}).`,
      `All-time \u2014 emotional ${data.emotional_avg}, cognitive ${data.cognitive_avg}, social ${data.social_avg}, communication ${data.communication_avg}, contextual ${data.contextual_avg}, artistic ${data.artistic_avg}`,
      `Last 30 days (${data.recent_sources_analyzed} sources) \u2014 emotional ${data.emotional_avg_recent}, cognitive ${data.cognitive_avg_recent}, social ${data.social_avg_recent}, communication ${data.communication_avg_recent}, contextual ${data.contextual_avg_recent}, artistic ${data.artistic_avg_recent}`
    ].join("\n");
    return { content: [{ type: "text", text }], structuredContent: { fingerprint: data } };
  }
});

// src/lib/mcp/tools/list-audio-sources.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_audio_sources_default = defineTool3({
  name: "list_audio_sources",
  title: "List my audio sources",
  description: "List the signed-in user's audio sources (Spotify/Apple tracks, uploads and ingested signals) with their analysis status, so the caller can see what is analyzed, pending or failed.",
  inputSchema: {
    limit: z2.number().int().describe("How many sources to return (1-50, default 15)").optional(),
    status: z2.enum(["pending", "processing", "complete", "failed"]).describe("Optional analysis-status filter.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const take = Math.min(Math.max(Math.round(limit ?? 15), 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("audio_sources").select("id, name, source_type, album_name, artists, analysis_status, analysis_error, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("analysis_status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map(
      (r) => `${r.name} \u2014 ${r.source_type} \u2014 ${r.analysis_status}` + (r.artists?.length ? ` \u2014 ${r.artists.join(", ")}` : "") + (r.analysis_error ? ` \u2014 error: ${r.analysis_error}` : "")
    ).join("\n") : "No audio sources yet.";
    return { content: [{ type: "text", text }], structuredContent: { sources: rows } };
  }
});

// src/lib/mcp/tools/search-taxonomy.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_taxonomy_default = defineTool4({
  name: "search_taxonomy",
  title: "Search the ontology taxonomy",
  description: "Search SonicSIM's semantic taxonomy (CTV, IAB, web and AudioSet branches) by label or dotted code, and report how well each node is grounded in real audio.",
  inputSchema: {
    query: z3.string().describe("Text to match against the node label or code, e.g. 'news' or 'ctv.genre'."),
    limit: z3.number().int().describe("How many nodes to return (1-50, default 15)").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated;
    const term = query.trim();
    if (!term) return { content: [{ type: "text", text: "query must not be empty." }], isError: true };
    const take = Math.min(Math.max(Math.round(limit ?? 15), 1), 50);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("taxonomy_nodes").select("code, label, parent_code, grounding_count, reviewed").eq("suppressed", false).or(`label.ilike.%${term}%,code.ilike.%${term}%`).order("grounding_count", { ascending: false }).limit(take);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map(
      (r) => `${r.code} \u2014 ${r.label ?? "(no label)"} \u2014 grounded in ${r.grounding_count} audio source(s)` + (r.reviewed ? " \u2014 reviewed" : "")
    ).join("\n") : `No taxonomy nodes matched "${term}".`;
    return { content: [{ type: "text", text }], structuredContent: { nodes: rows } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bskltmvfxolwhnfpsmno";
var mcp_default = defineMcp({
  name: "sonicsimai",
  title: "SonicSIMai",
  version: "0.1.0",
  instructions: "Tools for SonicSIM, a semantic audio analysis platform. Every audio source is scored across six categories \u2014 emotional, cognitive, social, communication, contextual, artistic \u2014 and mapped onto a semantic taxonomy. Use `list_analyses` for the signed-in user's recent scored sources, `get_fingerprint` for their aggregate sonic fingerprint, `list_audio_sources` to see what is analyzed or pending, and `search_taxonomy` to explore ontology nodes and their grounding. All tools act as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_analyses_default, get_fingerprint_default, list_audio_sources_default, search_taxonomy_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
